
<<<<<<< HEAD
name: Enterprise VID Issuer
=======
name: Enterprise Issuer
>>>>>>> master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
         registry: ghcr.io
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}}
    - uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
<<<<<<< HEAD
        tags: ghcr.io/gunet/enterprise-vid-issuer:latest
=======
        tags: ghcr.io/gunet/enterprise-issuer:latest
>>>>>>> master
